name: unicollab
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.1
  firebase: ^8.0.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  random_string: ^2.1.0
  firebase_dynamic_links: ^0.7.0+1
  firebase_storage: ^7.0.0
  file_picker: ^2.1.5+1
  path_provider: ^1.6.27
  cloud_functions: ^0.9.0
  open_file: ^3.0.3
  image_picker: ^0.6.7+21
  flutter_datetime_picker: ^1.5.0
  google_fonts: ^1.1.2
  mailer2: ^1.2.5
  cached_network_image: ^2.5.0
  sliding_up_panel: ^1.0.2
  provider: ^4.3.3
  google_sign_in: ^4.5.9
  flutter_speed_dial: ^2.1.1
  get_it: ^5.0.6
  share: ^0.6.5+4
  firebase_messaging:
  flutter_local_notifications: ^4.0.1+1
  firebase_admin: ^0.1.4
  marquee: ^1.7.0
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/logo.png

  fonts:
    - family: SFPro
      fonts:
        - asset: fonts/SFPro/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: fonts/SFPro/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: fonts/SFPro/SF-Pro-Display-Light.otf
          weight: 300
        - asset: fonts/SFPro/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: fonts/SFPro/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SFPro/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: fonts/SFPro/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: fonts/SFPro/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: fonts/SFPro/SF-Pro-Display-Black.otf
          weight: 900


